---
title: "Gulf Fisheries Centre Ageing Structures collection - Yellowtail Flounder"
author: "Daniel Ricard"
date: '`r paste0("Last modified timestap: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S"))`'
output: html_notebook
---

TO DO 2023
cod and friends - commercial 2022
cod and friends - observers 2022

```{r loaddata}
library(gulf)
```

## Yellowtail Flounder
Otoliths from the September RV survey, from other surveys, from sentinel programs and from port sampling of commercial fisheries and from at-sea observers.

Remaining issues:
- are there really no commercial otoliths between 1982 and 2018? 

```{r yellowtail, cache=TRUE}
## RV data
y <- read.card(species=42, card.type="bio", env="dev")#rv$bio[which(rv$bio$species ==42),]
rv.df <- aggregate(fish.number~year+month, data=y[which(y$age.material==1),], length)
names(rv.df) <- c("year_année", "month_mois", "number.otoliths_nombre.otolithes")
rv.df$source <- "RV-4T"

## commercial data
## what years are available for commercial ages?
## com.files <- list.files(path="//ENT.dfo-mpo.ca/dfo-mpo/GROUP/GLF/Regional_Shares/Science/Hd2/commercial/age", pattern="yelage")
y.c <- gulf::read.card(year=1982, sampling="commercial", species=42, card.type="age") ## this loads all pre-1982 commercial ages
for(yy in 2018:2022){ ## loop over years
  print(paste0("Year ",yy))
t.c <- gulf::read.card(year=yy, sampling="commercial", species=42, card.type="age")
y.c <- rbind(y.c,t.c)
}

l.4t <- which(substring(y.c$nafo.division,1,2)=="4T") ## keep only otoliths collected in NAFO 4T
comm.df <- aggregate(otolith.number~year+month, data=y.c[l.4t,], length)
names(comm.df) <- c("year_année", "month_mois", "number.otoliths_nombre.otolithes")
comm.df$source <- "Commercial"

## there is no observers otoliths for yellowtail

out.df <- rbind(rv.df, comm.df)
out.df$latin.name_nom.latin <- "Limanda ferruginea"
out.df$english.name_nom.anglais <- "Yellowtail Flounder"
out.df$french.name_nom.français <- "Limande à queue jaune"

vars <- c("source", "latin.name_nom.latin", "english.name_nom.anglais", "french.name_nom.français", "year_année","month_mois","number.otoliths_nombre.otolithes")
o1 <- order(out.df$source, out.df$year_année, out.df$month_mois)

out.fn <- "./data/NAFO-4T-Yellowtail-Flounder-otoliths.csv"
write.csv(out.df[o1,vars], file=out.fn, row.names = FALSE, fileEncoding = "UTF8")

## how many were actually aged?
#y <- read.card(species=42, card.type="bio", env="dev") #rv$bio[which(rv$bio$species==42),]
rv.df <- aggregate(fish.number~year+month, data=y[which(y$age.material==1),], length)
names(rv.df) <- c("year_année", "month_mois", "number.otoliths_nombre.otolithes")
rv.df2 <- aggregate(fish.number~year+month, data=y[which(y$age.material==1 & y$age %in% c(0:30)),], length)
names(rv.df2) <- c("year_année", "month_mois", "number.otoliths.aged_nombre.otolithes.agées")
m.rv.df <- merge(rv.df, rv.df2, all.x=TRUE, by=c("year_année","month_mois"))
m.rv.df$source <- "RV-4T"
m.rv.df[is.na(m.rv.df$number.otoliths.aged_nombre.otolithes.agées),"number.otoliths.aged_nombre.otolithes.agées"] <- 0

## do the same for commercial samples, how many were aged
l.4tvn <- which((substring(y.c$nafo.division,1,2)=="4T" | substring(y.c$nafo.division,1,3)=="4VN") & y.c$age %in% c(0:25)) 
comm.df2 <- aggregate(otolith.number~year+month, data=y.c[l.4tvn,], length)
names(comm.df2) <- c("year_année", "month_mois", "number.otoliths.aged_nombre.otolithes.agées")
m.comm.df <- merge(comm.df, comm.df2, all.x=TRUE, by=c("year_année","month_mois"))
m.comm.df$source <- "Commercial"
m.comm.df[is.na(m.comm.df$number.otoliths.aged_nombre.otolithes.agées),"number.otoliths.aged_nombre.otolithes.agées"] <- 0

out.df <- rbind(m.rv.df, m.comm.df)
out.df$latin.name_nom.latin <- "Limanda ferruginea"
out.df$english.name_nom.anglais <- "Yellowtail Flounder"
out.df$french.name_nom.français <- "Limande à queue jaune"

vars <- c("source", "latin.name_nom.latin", "english.name_nom.anglais", "french.name_nom.français", "year_année","month_mois","number.otoliths_nombre.otolithes","number.otoliths.aged_nombre.otolithes.agées")
o1 <- order(out.df$source, out.df$year_année, out.df$month_mois)

out.fn <- "./data/NAFO-4T-Yellowtail-Flounder-ages.csv"
write.csv(out.df[o1,vars], file=out.fn, row.names = FALSE, fileEncoding = "UTF8")

```

