---
title: "Gulf Fisheries Centre Ageing Structures collection"
author: "Daniel Ricard"
date: '`r paste0("Last modified timestap: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S"))`'
output: html_notebook
---

TO DO 2023
cod and friends - commercial 2022
cod and friends - observers 2022
white hake commercial 2020 and more recent

The [Ageing Structures collection held at the Gulf Fisheries Centre](https://dmapps/en/inventory/resources/8cc8a924-1dbf-11ea-9bf1-1860247f53e3/) consists in *Teleost* saggital otoliths and *Chondrichthyan* vertebrae. For certain species, the physical specimens held in the collection are often accompanied with digital images. The individual details associated with each structure consists in capture date and location, length of individual and usually includes additional variables such as weight and maturity status.

The purpose of this notebook is to facilitate the generation and update of the FGP datasets associated with the Ageing Structure collection.

## Data dictionary
Generate the data dictionary.

```{r dictionary, echo=TRUE, include=TRUE}
#################################################################
## data dictionary including the number of aged otoliths
vars.bilingual <- c("source", "latin.name_nom.latin", "english.name_nom.anglais", "french.name_nom.français", "year_année","month_mois","number.otoliths_nombre.otolithes","number.otoliths.aged_nombre.otolithes.agées")

data.dic <- data.frame(
  name_nom = vars.bilingual
  )
data.dic$description_fr <- c("Source des otolithes, peut soit provenir du relevé par navire de recherche dans la division 4T de l'OPANO (Research Vessel (RV-4T)), du relevé par navire de recherche dans les divisions 4RS de l'OPANO (Research Vessel (RV-4RS)), du relevé sentinelle de la division 4T de l'OPANO (SENT-4T),  d'échantillonnage des pêches commerciales (Commercial) ou d'observateurs en mer (Observateurs)", "Nom latin de l'espèce", "Nom anglais de l'espèce", "Nom français de l'espèce", "Année d'échantillonnage des otolithes", "Mois d'échantillonnage des otolithes", "Nombre d'otolithes dans la collection", "Nombre d'otolithes qui ont été agées")

data.dic$description_en <- c("Source of otoliths, can be either from the NAFO division 4T Research Vessel (RV-4T) survey, the NAFO divisions 4RS Research Vessel (RV-4RS) survey, the NAFO division 4T sentinel survey (SENT-4T), from commercial sampling (Commercial) or from at-sea observers (Observers)", "Latin name of the species", "English name of the species", "French name of the species", "Year when otoliths were collected", "Month when otolith were collected", "Number of otoliths in collection", "Number of otoliths that were aged")

data.dic.fn <- "data-dictionary.csv"
write.csv(data.dic, file=data.dic.fn, row.names = FALSE, fileEncoding = "UTF8")

#################################################################
## data dictionary for skates
vars.bilingual <- c("source", "latin.name_nom.latin", "english.name_nom.anglais", "french.name_nom.français", "year_année","month_mois","number.vertebrae_nombre.vertèbres")

data.dic <- data.frame(
  name_nom = vars.bilingual
  )
data.dic$description_fr <- c("Source des vertèbres, le relevé par navire de recherche (Research Vessel (RV))", "Nom latin de l'espèce", "Nom anglais de l'espèce", "Nom français de l'espèce", "Année d'échantillonnage des vertèbres", "Mois d'échantillonnage des vertèbres", "Nombre de vertèbres dans la collection")

data.dic$description_en <- c("Source of vertebrae, the Research Vessel (RV) survey", "Latin name of the species", "English name of the species", "French name of the species", "Year when vertebrae were collected", "Month when vertebrae were collected", "Number of vertebrae in collection")

data.dic.fn <- "data-dictionary-skates.csv"
write.csv(data.dic, file=data.dic.fn, row.names = FALSE, fileEncoding = "UTF8")

```

## Atlantic Cod

[Link to the metadata entry in the Science Data Inventory app](https://dmapps/en/inventory/resources/505/view/).

[Link to the notebook for Atlantic Cod](./Atlantic-Cod-otolith_notebook.nb.html),


## White Hake

[Link to the metadata entry in the Science Data Inventory app](https://dmapps/en/inventory/resources/506/view/).

[Link to the notebook for White Hake](./White-Hake-otolith_notebook.nb.html),

## American Plaice

[Link to the metadata entry in the Science Data Inventory app](https://dmapps/en/inventory/resources/420/view/).

[Link to the notebook for American Plaice](./American-Plaice-otolith_notebook.nb.html),

## Yellowtail Flounder

[Link to the metadata entry in the Science Data Inventory app](https://dmapps/en/inventory/resources/418/view/).

[Link to the notebook for Yellowtail Flounder](./Yellowtail-Flounder-otolith_notebook.nb.html),

## Winter Flounder

[Link to the metadata entry in the Science Data Inventory app](https://dmapps/en/inventory/resources/520/view/).

[Link to the notebook for Winter Flounder](./Winter-Flounder-otolith_notebook.nb.html),

## Witch Flounder

[Link to the metadata entry in the Science Data Inventory app](https://dmapps/en/inventory/resources/507/view/).

[Link to the notebook for Witch Flounder](./Witch-Flounder-otolith_notebook.nb.html),

## Chondrichthyan vertabrae

[Link to the metadata entry in the Science Data Inventory app](https://dmapps/en/inventory/resources/1483/view/).

[Link to the notebook for Chondrichthyan](./Skates-otolith_notebook.nb.html),

## Atlantic Herring

[Link to the metadata entry in the Science Data Inventory app](https://dmapps/en/inventory/resources/522/view/).

[Link to the notebook for Atlantic Herring](./Atlantic-Herring-otolith_notebook.nb.html),
